version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform format
          command: |
            terraform -chdir=terraform fmt -check=true
      - run:
          name: terraform init & plan
          command: |
            terraform -chdir=terraform init -input=false
            terraform -chdir=terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform -chdir=terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform -chdir=terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform -chdir=terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
          filters:
            branches:
              only: main
      - apply:
          requires:
            - hold-apply
          filters:
            branches:
              only: main
      - plan-destroy:
          requires:
            - apply
          filters:
            branches:
              only: main
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
          filters:
            branches:
              only: main
      - destroy:
          requires:
            - hold-destroy
          filters:
            branches:
              only: main
