version: 2

jobs:
  build:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - setup_remote_docker
      - run: aws --version
      - run:
          name: build image
          command: |
            docker build -t simple-prayer-service .
      - run:
          name: push to ECR
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com
            docker tag simple-prayer-service:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/simple-prayer-service:latest
            docker tag simple-prayer-service:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/simple-prayer-service:${CIRCLE_SHA1}
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/simple-prayer-service:latest
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/simple-prayer-service:${CIRCLE_SHA1}
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform format
          command: |
            terraform -chdir=terraform fmt -check=true
      - run:
          name: terraform init & plan
          command: |
            terraform -chdir=terraform init -input=false
            terraform -chdir=terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init
          command: |
            terraform -chdir=terraform init -input=false
      - run:
          name: terraform plan
          command: |
            terraform -chdir=terraform plan -out tfapply
      - run:
          name: terraform apply
          command: |
            terraform -chdir=terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform -chdir=terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform -chdir=terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - build
      - plan-apply:
          requires:
            - build
      - hold-apply:
          type: approval
          requires:
            - plan-apply
          filters:
            branches:
              only: main
      - apply:
          requires:
            - hold-apply
          filters:
            branches:
              only: main
      # - plan-destroy:
      #     requires:
      #       - apply
      #     filters:
      #       branches:
      #         only: main
      # - hold-destroy:
      #     type: approval
      #     requires:
      #       - plan-destroy
      #     filters:
      #       branches:
      #         only: main
      # - destroy:
      #     requires:
      #       - hold-destroy
      #     filters:
      #       branches:
      #         only: main
